package com.sakila.utility;

public enum SceneView {

    CREATECUSTOMER,
    CREATECUSTOMERUSER,
    UPDATECUSTOMER,
    CREATEFILM,
    UPDATEFILM,
    CREATERENTAL,
    UPDATERENTAL,
    CREATEINVENTORY,
    UPDATEINVENTORY,
    UPDATEACTOR,
    CREATEACTOR,


}
